services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog1234
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  prod-web:
    container_name: blog-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
